# The intended use of resource registry is to launch this with all low level drivers
# Then get params like rospy.get_param("/PARAM/LED_SERVICE")
SERVICE:
  LED_SERVICE: "/dream/led_service"

TOPIC:
  ENCODER_STATUS: "/dream/encoder_status"
