# The intended use of resource registry is to launch this with all low level drivers
# Then get params like rospy.get_param("/PARAM/LED_SERVICE")
# rosparam load dream_resource_registry.yaml
SERVICE:
  LED_SERVICE: "/dream/led_service"

ROS_TOPIC:
  WHEEL_VELOCITIES: "/dream/wheel_velocities"
  CMD_VEL: "/dream/cmd_vel"
  ODOM: "/dream/odom"
  WHEEL_POS: "/dream/wheel_pos"
  SCAN_TOPIC: "/dream/scan"

SHM_TOPIC:
  # NOTE: there must be only one slash, and it should be at the beginning
  WHEEL_VELOCITIES: "/wheel_velocities"
  WHEEL_POS: "/wheel_pos"
  COMMANDED_WHEEL_VELOCITY: "/commanded_wheel_velocity"
  MOTOR_COMMANDS: "/motor_commands"

PARAMS:
  ENCODER_PUB_FREQUENCY: 30
  MOTOR_PUB_FREQUENCY: 20
  WHEEL_DIAMETER: 0.041
  # Useful for localization
  WHEEL_BASE_WITH_THICKNESS: 0.23
  WHEEL_THICKNESS: 0.040
  WHEEL_BASE_CENTER_TO_CENTER: 0.190
  DEBUG_MOTORS: true
  SCAN_FRAME: "scan"
