# The intended use of resource registry is to launch this with all low level drivers
# Then get params like rospy.get_param("/PARAM/LED_SERVICE")
SERVICE:
  LED_SERVICE: "/dream/led_service"

ROS_TOPIC:
  WHEEL_VELOCITIES: "/dream/wheel_velocities"
  CMD_VEL: "/dream/cmd_vel"

SHM_TOPIC:
  # NOTE: there must be only one slash, and it should be at the beginning
  WHEEL_VELOCITIES: "/dream/wheel_velocities"
  COMMANDED_WHEEL_VELOCITY: "/dream/commanded_wheel_velocity"
  MOTOR_COMMANDS: "/dream/motor_commands"

PARAMS:
  ENCODER_PUB_FREQUENCY: 50
  MOTOR_PUB_FREQUENCY: 15
  WHEEL_DIAMETER: 0.041
  # Useful for localization
  WHEEL_BASE_WITH_THICKNESS: 0.23
  WHEEL_THICKNESS: 0.040
  WHEEL_BASE_CENTER_TO_CENTER: 0.190
