# The intended use of resource registry is to launch this with all low level drivers
# Then get params like rospy.get_param("/PARAM/LED_SERVICE")
SERVICE:
  LED_SERVICE: "/dream/led_service"

SHM_TOPIC:
  # NOTE: there must be only one slash, and it should be at the beginning
  ENCODER_STATUS: "/encoder_status"
  MOTOR_COMMANDS: "/motor_commands"
